title: Nature Love
email: narutouzu50987@gmail.com
description: "Nature Love"
baseurl: "/"
url: "https://naturelovewsp.github.io"
github_username:  Nature Love
author: Nature Love


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
